# Generated by Django 5.0.4 on 2024-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='default_address', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='default_sity', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='default_first_name', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='default_last_name', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default='default_postal_code', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
